FROM python:3.7-alpine

COPY ./scrapper/requirements.txt .

RUN pip install -r /requirements.txt

COPY ./scrapper/app /app

WORKDIR /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4557"]