module.exports = [
  {
    userId: 1,
    symbol: 373019,
    amount: 2,
    price: 184.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    userId: 1,
    symbol: 373019,
    amount: 1,
    price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    userId: 1,
    symbol: 373019,
    amount: 1,
    price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    userId: 1,
    symbol: 1100957,
    amount: 2,
    price: 325.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    userId: 1,
    symbol: 1100957,
    amount: 2,
    price: 322.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    userId: 2,
    symbol: 373019,
    amount: 2,
    price: 184.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    userId: 2,
    symbol: 373019,
    amount: 1,
    price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    userId: 2,
    symbol: 373019,
    amount: 1,
    price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    userId: 2,
    symbol: 1100957,
    amount: 2,
    price: 325.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    userId: 2,
    symbol: 1100957,
    amount: 3,
    price: 322.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
