module.exports = [
  {
    user_id: 1,
    symbol: 373019,
    buy_amount: 2,
    buy_price: 184.8,
    operation: "buy",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 1,
    symbol: 373019,
    buy_amount: 1,
    operation: "buy",
    buy_price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 1,
    symbol: 373019,
    sell_amount: 1,
    operation: "sell",
    sell_price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 1,
    symbol: 1100957,
    buy_amount: 2,
    operation: "buy",
    buy_price: 325.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 1,
    symbol: 1100957,
    buy_amount: 2,
    operation: "buy",
    buy_price: 322.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 2,
    symbol: 373019,
    buy_amount: 2,
    operation: "buy",
    buy_price: 184.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 2,
    symbol: 373019,
    operation: "buy",
    buy_amount: 1,
    buy_price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 2,
    symbol: 373019,
    sell_amount: 1,
    operation: "sell",
    sell_price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  
  {
    user_id: 2,
    operation: "buy",
    symbol: 1100957,
    buy_amount: 2,
    sell_amount: 0,
    buy_price: 325.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 2,
    symbol: 1100957,
    buy_amount: 3,
    operation: "buy",
    buy_price: 322.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
