module.exports = [
  {
    user_id: 1,
    symbol: 373019,
    amount: 2,
    price: 184.8,
    operation: "buy",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 1,
    symbol: 373019,
    amount: 1,
    operation: "buy",
    price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 1,
    symbol: 373019,
    amount: -1,
    operation: "sell",
    price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 1,
    symbol: 1100957,
    amount: 2,
    operation: "buy",
    price: 325.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 1,
    symbol: 1100957,
    amount: 2,
    operation: "buy",
    price: 322.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 2,
    symbol: 373019,
    amount: 2,
    operation: "buy",

    price: 184.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 2,
    symbol: 373019,
    operation: "buy",
    amount: 1,
    price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 2,
    symbol: 373019,
    amount: -1,
    operation: "sell",
    price: 183.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 2,
    operation: "buy",
    symbol: 1100957,
    amount: 2,
    price: 325.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: 2,
    symbol: 1100957,
    amount: 3,
    operation: "buy",
    price: 322.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
